-- Create token_mentions table
CREATE TABLE IF NOT EXISTS public.token_mentions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    count INTEGER NOT NULL DEFAULT 0,
    messages JSONB NOT NULL DEFAULT '[]'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add indexes for better query performance
-- CREATE INDEX IF NOT EXISTS idx_token_mentions_symbol ON token_mentions(symbol);
-- CREATE INDEX IF NOT EXISTS idx_token_mentions_count ON token_mentions(count);
-- CREATE INDEX IF NOT EXISTS idx_token_mentions_created_at ON token_mentions(created_at);

-- Enable RLS
ALTER TABLE public.token_mentions ENABLE ROW LEVEL SECURITY;

-- Create policy to allow all operations
DO $$
BEGIN
    CREATE POLICY "Allow all operations for authenticated users"
    ON public.token_mentions
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);
EXCEPTION
    WHEN duplicate_object THEN
        RAISE NOTICE 'Policy "Allow all operations for authenticated users" on public.token_mentions already exists, skipping.';
END
$$; 